# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gomod"

    # Location of package manifests
    directory: "/"

    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Asia/Tbilisi"

    # Raise pull requests for version updates
    # to gomod against the `main` branch
    target-branch: "main"

    commit-message:
      # Prefix all commit messages with "deeps: "
      prefix: "deps"

    # Specify labels for npm pull requests
    labels:
      - "dependencies"

    # Allow up to 10 open pull requests for pip dependencies
    open-pull-requests-limit: 10

    # Add reviewers
    reviewers:
      - "LukaGiorgadze"
