name: Go mod

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Verify dependencies
        run: |
          go clean --modcache
          GOWORK=off go mod verify